-- Sample clients with social media and complete information
-- Run this after your clients table migration

INSERT INTO clients (
    fName, 
    lName, 
    address, 
    apt, 
    city, 
    state, 
    zip, 
    phone, 
    phone2, 
    email, 
    instagram, 
    facebook, 
    twitter, 
    tiktok, 
    linkedin, 
    notes,
    created_at,
    updated_at
) VALUES 
(
    'Sarah', 
    'Johnson', 
    '123 Main Street', 
    NULL, 
    'Los Angeles', 
    'CA', 
    '90210', 
    '(555) 123-4567', 
    NULL, 
    'sarah.johnson@email.com',
    '@sarahjohnson_',
    'sarah.johnson.official',
    '@sarahj_styles',
    NULL,
    'linkedin.com/in/sarah-johnson',
    'Regular client, prefers morning appointments. Allergic to sulfates.',
    NOW(),
    NOW()
),
(
    'Maria', 
    'Rodriguez', 
    '456 Oak Avenue', 
    'Apt 2B', 
    'Beverly Hills', 
    'CA', 
    '90211', 
    '(555) 987-6543', 
    '(555) 111-2222', 
    'maria.rodriguez@gmail.com',
    '@maria_beauty',
    'maria.rodriguez.hair',
    NULL,
    '@mariabeauty22',
    NULL,
    'Loves bold colors and creative cuts. Frequent color changes.',
    NOW(),
    NOW()
),
(
    'Jessica', 
    'Chen', 
    '789 Palm Drive', 
    NULL, 
    'Hollywood', 
    'CA', 
    '90028', 
    '(555) 456-7890', 
    NULL, 
    'jessica.chen@yahoo.com',
    '@jessicachen_hair',
    NULL,
    '@jess_chen',
    NULL,
    'linkedin.com/in/jessicachen',
    'Professional headshots coming up - needs polished look.',
    NOW(),
    NOW()
),
(
    'Amanda', 
    'Williams', 
    '321 Sunset Boulevard', 
    'Unit 15', 
    'West Hollywood', 
    'CA', 
    '90069', 
    '(555) 234-5678', 
    '(555) 333-4444', 
    'amanda.w@outlook.com',
    '@amandawilliams',
    'amanda.williams.beauty',
    '@amandaw_styles',
    '@amandawbeauty',
    'linkedin.com/in/amandawilliams',
    'Wedding coming up in 3 months. Wants to grow hair out.',
    NOW(),
    NOW()
),
(
    'Taylor', 
    'Davis', 
    '654 Melrose Place', 
    NULL, 
    'Los Angeles', 
    'CA', 
    '90038', 
    '(555) 345-6789', 
    NULL, 
    'taylor.davis@email.com',
    NULL,
    'taylor.davis.la',
    NULL,
    '@taylordavis_',
    NULL,
    'Sensitive scalp - uses only organic products.',
    NOW(),
    NOW()
);